services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .docker.env
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wantogo

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .docker.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - wantogo

volumes:
  postgres_data:
  pgadmin_data:
networks:
  wantogo: